# Generated by Django 6.0.3 on 2026-03-25 06:07

import admin_dashboard.models
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Banner_video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        upload_to="Banner_videos/",
                        validators=[admin_dashboard.models.validate_mp4],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
                ),
                ("image", models.ImageField(null=True, upload_to="blog_images/")),
                ("video_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.CharField(blank=True, max_length=300)),
                ("show_cta", models.BooleanField(default=False)),
                ("cta_text", models.CharField(blank=True, max_length=100)),
                ("cta_link", models.URLField(blank=True)),
                ("comment_show_status", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                        ],
                        max_length=20,
                    ),
                ),
                ("category", models.CharField(max_length=200)),
                ("experience_required", models.CharField(max_length=100)),
                (
                    "salary_range",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("job_summary", models.TextField()),
                ("roles_responsibilities", models.TextField()),
                ("skills_required", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("posted_date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmailSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_selected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LocationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(blank=True, max_length=100, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("current_location", models.CharField(max_length=200)),
                ("professional_details", models.TextField()),
                ("total_experience", models.CharField(max_length=50)),
                ("highest_qualification", models.CharField(max_length=200)),
                (
                    "notice_period",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("resume", models.FileField(upload_to="resumes/")),
                ("applied_on", models.DateTimeField(auto_now_add=True)),
                ("is_seen", models.BooleanField(default=False)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="admin_dashboard.career",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("project_config", models.CharField(max_length=255)),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("villa", "Villa"),
                            ("plot", "Plot"),
                            ("form_land", "Form Land"),
                            ("form_house", "Form House"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "project_status",
                    models.CharField(
                        choices=[
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("up_comming", "Up Comming"),
                        ],
                        default="completed",
                        max_length=50,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("location", models.CharField(max_length=150)),
                ("full_location", models.TextField()),
                ("description", models.TextField()),
                ("total_units", models.PositiveIntegerField(blank=True, null=True)),
                ("sold_units", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "construction_status",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "project_video",
                    models.FileField(
                        blank=True, null=True, upload_to="projects/videos/"
                    ),
                ),
                (
                    "brochure",
                    models.FileField(
                        blank=True, null=True, upload_to="projects/brochures/"
                    ),
                ),
                ("image1", models.ImageField(upload_to="projects/images/")),
                ("image2", models.ImageField(upload_to="projects/images/")),
                ("image3", models.ImageField(upload_to="projects/images/")),
                (
                    "google_map_location",
                    models.TextField(
                        help_text="Paste embed iframe or Google Maps link"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "amenities",
                    models.ManyToManyField(blank=True, to="admin_dashboard.amenity"),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LocationAdvantage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("distance", models.CharField(max_length=50)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advantages",
                        to="admin_dashboard.locationcategory",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_advantages",
                        to="admin_dashboard.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="projects/gallery/")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="admin_dashboard.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FloorPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="projects/floor_plans/")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floor_plans",
                        to="admin_dashboard.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_seen", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_dashboard.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project_Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("mobile_number", models.CharField(max_length=20)),
                ("budget", models.CharField(blank=True, max_length=100, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enquiries",
                        to="admin_dashboard.project",
                    ),
                ),
            ],
        ),
    ]
