# Generated by Django 6.0.3 on 2026-03-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="sq_ft",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="total_plots",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
