# Generated by Django 5.2.8 on 2026-03-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0003_project_project_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_config",
            field=models.CharField(default="3 BHK | 1368 TO 1700", max_length=255),
            preserve_default=False,
        ),
    ]
