# Generated by Django 5.2.8 on 2026-03-20 12:10

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "admin_dashboard",
            "0008_project_construction_status_project_sold_units_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
                ),
                ("image", models.ImageField(null=True, upload_to="blog_images/")),
                ("video_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.CharField(blank=True, max_length=300)),
                ("show_cta", models.BooleanField(default=False)),
                ("cta_text", models.CharField(blank=True, max_length=100)),
                ("cta_link", models.URLField(blank=True)),
                ("comment_show_status", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
