# Generated by Django 5.2.8 on 2026-03-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0011_emailsetting_contact_project_enquiry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="project",
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(default=1, verbose_name=20),
            preserve_default=False,
        ),
    ]
