# Generated by Django 5.2.8 on 2026-03-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0012_remove_contact_project_alter_contact_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("apartment", "Apartment"),
                    ("villa", "Villa"),
                    ("plot", "Plot"),
                    ("form_land", "Form Land"),
                    ("form_house", "Form House"),
                ],
                max_length=50,
            ),
        ),
    ]
