# Generated by Django 5.2.8 on 2026-03-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0014_alter_project_options_project_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="project_enquiry",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project_enquiry",
            name="budget",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
