# Generated by Django 5.2.8 on 2026-03-24 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "admin_dashboard",
            "0015_project_enquiry_message_alter_project_enquiry_budget",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project_enquiry",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enquiries",
                to="admin_dashboard.project",
            ),
        ),
    ]
