# Generated by Django 5.2.8 on 2026-03-24 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0016_alter_project_enquiry_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="admin_dashboard.project",
            ),
            preserve_default=False,
        ),
    ]
