# Generated by Django 5.2.8 on 2026-03-19 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("villa", "Villa"),
                            ("plot", "Plot"),
                            ("commercial", "Commercial"),
                        ],
                        max_length=50,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("location", models.CharField(max_length=150)),
                ("full_location", models.TextField()),
                (
                    "project_video",
                    models.FileField(
                        blank=True, null=True, upload_to="projects/videos/"
                    ),
                ),
                (
                    "brochure",
                    models.FileField(
                        blank=True, null=True, upload_to="projects/brochures/"
                    ),
                ),
                ("image1", models.ImageField(upload_to="projects/images/")),
                ("image2", models.ImageField(upload_to="projects/images/")),
                ("image3", models.ImageField(upload_to="projects/images/")),
                (
                    "google_map_location",
                    models.TextField(
                        help_text="Paste embed iframe or Google Maps link"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "amenities",
                    models.ManyToManyField(blank=True, to="admin_dashboard.amenity"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocationAdvantage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("school", "School"),
                            ("college", "College"),
                            ("hospital", "Hospital"),
                            ("transport", "Transport"),
                            ("shopping", "Shopping"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("distance", models.CharField(max_length=50)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_advantages",
                        to="admin_dashboard.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="projects/gallery/")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="admin_dashboard.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FloorPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="projects/floor_plans/")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floor_plans",
                        to="admin_dashboard.project",
                    ),
                ),
            ],
        ),
    ]
