# Generated by Django 5.2.8 on 2026-03-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0002_amenity_project_locationadvantage_gallery_floorplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_status",
            field=models.CharField(
                choices=[
                    ("ongoing", "Ongoing"),
                    ("completed", "Completed"),
                    ("up_comming", "Up Comming"),
                ],
                default="completed",
                max_length=50,
            ),
        ),
    ]
