# Generated by Django 5.2.8 on 2026-03-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0004_project_project_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(default="data"),
            preserve_default=False,
        ),
    ]
