# Generated by Django 5.2.8 on 2026-03-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0005_project_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="amenity",
            name="icon",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
