# Generated by Django 5.2.8 on 2026-03-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0007_locationcategory_alter_locationadvantage_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="construction_status",
            field=models.PositiveIntegerField(
                blank=True, help_text="Enter percentage (0–100)", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="sold_units",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="total_units",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
